package bitcoin

import examples.commons.{Nonce, PublicKey25519NoncedBox, Value}
import examples.bitcoin.state.BitcoinBoxStoredState
import io.iohk.iodb.LSMStore
import org.scalacheck.Gen
import scorex.core.transaction.box.proposition.PublicKey25519Proposition
import scorex.core.transaction.state.{BoxStateChanges, Insertion, PrivateKey25519, PrivateKey25519Companion}
import scorex.testkit.generators.CoreGenerators

import scala.util.Random

trait StateGenerators extends StoreGenerators with CoreGenerators{this: HybridGenerators with CoreGenerators with StoreGenerators =>

  private val valueSeed = 5000000
  /**
    * Generate a BitcoinBoxStoredState containing 10000 random boxes.
    * In these boxes, the priv, pub key is generated by privKey.
    * valueSeed is set to be very large, meaning in the boxes, there are large amount of tokens.
    */
  @SuppressWarnings(Array("org.wartremover.warts.OptionPartial"))
  val stateGen: Gen[BitcoinBoxStoredState] =
    for {
      dir <- tempDirGen
      keepVersions <- Gen.chooseNum(5, 20)
    } yield {
      def randomBox(): PublicKey25519NoncedBox = {
        val value: Value = Value @@ (Random.nextInt(valueSeed) + valueSeed).toLong
        val nonce: Nonce = Nonce @@ Random.nextLong()
        val keyPair = privKey(value)
        PublicKey25519NoncedBox(keyPair._2, nonce, value)
          .ensuring(box => PrivateKey25519Companion.owns(keyPair._1, box))
      }

      val store = new LSMStore(dir, keepVersions = keepVersions)
      val s0 = BitcoinBoxStoredState(store, versionTagGen.sample.get)
      val inserts = (1 to 10000)
        .map(_ => Insertion[PublicKey25519Proposition, PublicKey25519NoncedBox](randomBox()))
      s0.applyChanges(BoxStateChanges(inserts), versionTagGen.sample.get).get
    }
}
